#!/usr/bin/env bash
# report.sh — Generate a personalized OpenClaw upgrade report
# Usage: ./scripts/report.sh [--output FILE] [--compare]

set -euo pipefail

WORKSPACE_ROOT="${OPENCLAW_WORKSPACE:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

OUTPUT="" COMPARE=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)  OUTPUT="$2"; shift 2 ;;
    --compare) COMPARE=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Run audit and capture output
AUDIT_OUTPUT=$(bash "${WORKSPACE_ROOT}/skills/openclaw-optimizer/scripts/audit.sh" 2>/dev/null || echo "Audit failed")

# Extract score
CURRENT_SCORE=$(echo "$AUDIT_OUTPUT" | grep '^Score:' | head -1 | sed 's/Score: //')
PERCENTAGE=$(echo "$AUDIT_OUTPUT" | grep '^Rating:' | head -1 | sed 's/Rating: //')

REPORT=$(cat << EOF
# OpenClaw Optimizer Report

**Generated**: $(date '+%Y-%m-%d %H:%M')
**Workspace**: ${WORKSPACE_ROOT}
**Current Score**: ${CURRENT_SCORE} (${PERCENTAGE})

## Audit Results

${AUDIT_OUTPUT}

## Quick Fixes

Run these commands to improve your setup:

\`\`\`bash
# Apply all safe fixes at once
./skills/openclaw-optimizer/scripts/fix.sh --all-safe

# Or apply individually:
./skills/openclaw-optimizer/scripts/fix.sh --fix "create-memory-md"
./skills/openclaw-optimizer/scripts/fix.sh --fix "create-user-profile"
./skills/openclaw-optimizer/scripts/fix.sh --fix "create-data-dirs"
\`\`\`

## Install Recommended Skills

\`\`\`bash
# Self-improvement pipeline
pepeclaw install realtime-learning execution-trace self-scoring skill-autocreator

# Workspace awareness
pepeclaw install deep-search user-modeling

# Optimization
pepeclaw install openclaw-optimizer nightly-evolution
\`\`\`

---
*Generated by openclaw-optimizer*
EOF
)

if [[ -n "$OUTPUT" ]]; then
  echo "$REPORT" > "$OUTPUT"
  echo "Report saved to: ${OUTPUT}"
else
  echo "$REPORT"
fi
